flowchart LR
    alice["<b>alice</b><br/><u>person</u><br/><i>name: Alice</i><br/><i>age: 34</i>"]
    bob["<b>bob</b><br/><u>person</u><br/><i>name: Bob</i><br/><i>age: 32</i>"]
    luna["<b>luna</b><br/><u>dog</u><br/><i>name: Luna</i><br/><i>cute: true</i>"]
    alice -- "<u>friends</u><br/><i>since: 2020</i>" --- bob
    alice -- "<u>owns</u>" --> luna
